export const PRODCUT_LIST_REQUEST = 'PRODCUT_LIST_REQUEST'
export const PRODCUT_LIST_SUCCESS = 'PRODCUT_LIST_SUCCESS'
export const PRODCUT_LIST_FAIL = 'PRODCUT_LIST_FAIL'

export const PRODCUT_DETAILS_REQUEST = 'PRODCUT_DETAILS_REQUEST'
export const PRODCUT_DETAILS_SUCCESS = 'PRODCUT_DETAILS_SUCCESS'
export const PRODCUT_DETAILS_FAIL = 'PRODCUT_DETAILS_FAIL'

export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST'
export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS'
export const PROJECT_LIST_FAIL = 'PROJECT_LIST_FAIL'

export const ALL_PROJECT_LIST_REQUEST = 'ALL_PROJECT_LIST_REQUEST'
export const ALL_PROJECT_LIST_SUCCESS = 'ALL_PROJECT_LIST_SUCCESS'
export const ALL_PROJECT_LIST_FAIL = 'ALL_PROJECT_LIST_FAIL'

export const BOARD_CHANGE_CURRENT = 'BOARD_CHANGE_CURRENT'

export const BOARD_LIST_REQUEST = 'BOARD_LIST_REQUEST'
export const BOARD_LIST_SUCCESS = 'BOARD_LIST_SUCCESS'
export const BOARD_LIST_FAIL = 'BOARD_LIST_FAIL'

export const BOARD_LIST_IN_PROJECT_REQUEST = 'BOARD_LIST_IN_PROJECT_REQUEST'
export const BOARD_LIST_IN_PROJECT_SUCCESS = 'BOARD_LIST_IN_PROJECT_SUCCESS'
export const BOARD_LIST_IN_PROJECT_FAIL = 'BOARD_LIST_IN_PROJECT_FAIL'

export const BOARD_CREATE_REQUEST = 'BOARD_CREATE_REQUEST'
export const BOARD_CREATE_SUCCESS = 'BOARD_CREATE_SUCCESS'
export const BOARD_CREATE_FAIL = 'BOARD_CREATE_FAIL'
export const BOARD_CREATE_RESET = 'BOARD_CREATE_RESET'

export const COLUMN_LIST_REQUEST = 'COLUMN_LIST_REQUEST'
export const COLUMN_LIST_SUCCESS = 'COLUMN_LIST_SUCCESS'
export const COLUMN_LIST_FAIL = 'COLUMN_LIST_FAIL'
export const COLUMN_LIST_RESET = 'COLUMN_LIST_RESET'

export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST'
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS'
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL'

export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL'
export const TASK_CREATE_RESET = 'TASK_CREATE_RESET'

export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL'
export const TASK_DELETE_RESET = 'TASK_DELETE_RESET'

export const COLUMN_CREATE_REQUEST = 'COLUMN_CREATE_REQUEST'
export const COLUMN_CREATE_SUCCESS = 'COLUMN_CREATE_SUCCESS'
export const COLUMN_CREATE_FAIL = 'COLUMN_CREATE_FAIL'
export const COLUMN_CREATE_RESET = 'COLUMN_CREATE_RESET'

export const COLUMN_DELETE_SUCCESS = 'COLUMN_DELETE_SUCCESS'
export const COLUMN_DELETE_FAIL = 'COLUMN_DELETE_FAIL'
export const COLUMN_DELETE_RESET = 'COLUMN_DELETE_RESET'

export const COLUMN_UPDATE_REQUEST = 'COLUMN_UPDATE_REQUEST'
export const COLUMN_UPDATE_SUCCESS = 'COLUMN_UPDATE_SUCCESS'
export const COLUMN_UPDATE_FAIL = 'COLUMN_UPDATE_FAIL'
export const COLUMN_UPDATE_RESET = 'COLUMN_UPDATE_RESET'

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_REQUEST'
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS'
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL'
export const TASK_UPDATE_RESET = 'TASK_UPDATE_RESET'

export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST'
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS'
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL'
export const COMMENT_CREATE_RESET = 'COMMENT_CREATE_RESET'

export const ROLE_CREATE_REQUEST = 'ROLE_CREATE_REQUEST'
export const ROLE_CREATE_SUCCESS = 'ROLE_CREATE_SUCCESS'
export const ROLE_CREATE_FAIL = 'ROLE_CREATE_FAIL'
export const ROLE_CREATE_RESET = 'ROLE_CREATE_RESET'

export const ROLE_LIST_REQUEST = 'ROLE_LIST_REQUEST'
export const ROLE_LIST_SUCCESS = 'ROLE_LIST_SUCCESS'
export const ROLE_LIST_FAIL = 'ROLE_LIST_FAIL'

export const ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS'
export const ROLE_DELETE_FAIL = 'ROLE_DELETE_FAIL'
export const ROLE_DELETE_RESET = 'ROLE_DELETE_RESET'

export const USER_ROLE_LIST_REQUEST = 'USER_ROLE_LIST_REQUEST'
export const USER_ROLE_LIST_SUCCESS = 'USER_ROLE_LIST_SUCCESS'
export const USER_ROLE_LIST_FAIL = 'USER_ROLE_LIST_FAIL'

export const PROJECT_INFO_UPDATE_REQUEST = 'PROJECT_INFO_UPDATE_REQUEST'
export const PROJECT_INFO_UPDATE_SUCCESS = 'PROJECT_INFO_UPDATE_SUCCESS'
export const PROJECT_INFO_UPDATE_FAIL = 'PROJECT_INFO_UPDATE_FAIL'
export const PROJECT_INFO_UPDATE_RESET = 'PROJECT_INFO_UPDATE_RESET'