# Generated by Django 4.1.7 on 2023-05-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_task_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
