# Generated by Django 4.1.7 on 2023-05-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.ManyToManyField(to='base.file'),
        ),
    ]
