# Generated by Django 4.1.7 on 2023-05-27 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_remove_comment_file_file_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRoles',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, choices=[('PM', 'PM'), ('Employee', 'Employee'), ('Spectator', 'Spectator')], max_length=15, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
