# Generated by Django 4.1.7 on 2023-05-27 06:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_usersroles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersRoles',
            new_name='UsersRole',
        ),
    ]
